name: CI
on:
  push:
    branches: [selenium]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.3.0
      - name: Install
        run: npm install
      - name: Run frontend
        run: (npm run start&)
      - name: Install E2E
        run: npm install
        working-directory: e2e
      - name: Run e2e tests
        run: npm run wdio
        working-directory: e2e
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: logs
